export enum TokenKind {
  LeftParenthesis = 'LeftParenthesis',
  RightParenthesis = 'RightParenthesis',
  LeftBracket = 'LeftBracket',
  RightBracket = 'RightBracket',
  LeftBrace = 'LeftBrace',
  RightBrace = 'RightBrace',
  Question = 'Question',
  Colon = 'Colon',
  Comma = 'Comma',
  DoubleAmpersand = 'DoubleAmpersand',
  DoublePipe = 'DoublePipe',
  DoubleQuestion = 'DoubleQuestion',
  Dot = 'Dot',
  Equal = 'Equal',
  NotEqual = 'NotEqual',
  Less = 'Less',
  LessOrEqual = 'LessOrEqual',
  Greater = 'Greater',
  GreaterOrEqual = 'GreaterOrEqual',
  Plus = 'Plus',
  Minus = 'Minus',
  Asterisk = 'Asterisk',
  Slash = 'Slash',
  Percent = 'Percent',
  Bang = 'Bang',
  LiteralFloat = 'LiteralFloat',
  LiteralInt = 'LiteralInt',
  LiteralUInt = 'LiteralUInt',
  LiteralString = 'LiteralString',
  BytesSequence = 'BytesSequence',
  False = 'False',
  True = 'True',
  Null = 'Null',
  In = 'In',
  As = 'As',
  Break = 'Break',
  Const = 'Const',
  Continue = 'Continue',
  Else = 'Else',
  For = 'For',
  Function = 'Function',
  If = 'If',
  Import = 'Import',
  Let = 'Let',
  Loop = 'Loop',
  Package = 'Package',
  Namespace = 'Namespace',
  Return = 'Return',
  Var = 'Var',
  Void = 'Void',
  While = 'While',
  Identifier = 'Identifier',
  Whitespace = 'Whitespace',
  Comment = 'Comment',
  Unrecognized = 'Unrecognized',
}

const LITERALS: ReadonlySet<TokenKind> = new Set([
  TokenKind.LiteralFloat,
  TokenKind.LiteralInt,
  TokenKind.LiteralUInt,
  TokenKind.LiteralString,
  TokenKind.BytesSequence,
  TokenKind.True,
  TokenKind.False,
  TokenKind.Null,
])

export function isLiteral(kind: TokenKind): boolean {
  return LITERALS.has(kind)
}
