export enum ExpressionKind {
  Conditional = 'Conditional',
  Binary = 'Binary',
  Unary = 'Unary',
  Parenthesized = 'Parenthesized',
  StringLiteral = 'StringLiteral',
  BytesLiteral = 'BytesLiteral',
  FloatLiteral = 'FloatLiteral',
  IntLiteral = 'IntLiteral',
  UIntLiteral = 'UIntLiteral',
  BoolLiteral = 'BoolLiteral',
  NullLiteral = 'NullLiteral',
  Identifier = 'Identifier',
  MemberAccess = 'MemberAccess',
  Index = 'Index',
  Call = 'Call',
  List = 'List',
  Map = 'Map',
  Message = 'Message',
}
